### ISSUE TITLE
[M3: R]

### ISSUE THREAD

**Issue by slumnitz** [UBC-MDS/DSCI532_World_Wide_Weapons_Report_R#12]
Hello everyone,

I am curious how your R-app works out, this is an interesting dataset! You are doing a great job using issues, documenting and merging each others PR's.

Please note, if you have the feeling you are running out of time, I would suggest to focus on implementing interactivity for 2 visualisations, i.e. the choropleth and one of the graphs.

Notes for improvement on the next iteration:
* make sure to change all Python references in your readme to an R reference
* you README.md was supposed to include your current R draft visualisation, and your submission a link comparing your two proposals (even if nothing changed). Make sure to read through the instructions carefully next time to not loose marks.

Please let me know if you have any questions by tagging me in issues.

**Comment by slbsolomon** [comment]
Hi Stefanie,

Thanks for the feedback! Our README.md and proposal.md documents were updated in #13 to reflect that this is an R dashboard. I am closing this issue, but feel free to open a new issue with any further comments.

Thanks!
